Comment out the line that makes error
The name Opuntia21277 is used more than once in the fasta file. Second and later occurrences are appended a _number

LTR85.lib already exists!
ERROR: CRL_Step5.pl exited non-zero